App/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path


urlpatterns = [
    path('', views.home,name='home'),
    path('report/',views.report,name='report'),
    path('addWaste/',views.addWaste,name='addwaste'),
    path('schedule/',views.schedule,name='schedule'),
    path('manage/',views.manager,name='manager'),
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logOutUser,name='logout'),
    path('register/',views.register,name='register'),
    path('User/Profile/',views.ProfilePage,name='profile'),
    path('User/Subscriptions/',views.subscriptions,name='subscriptions'),
    path('User/Analytics/',views.Charts,name='charts'),
    path('User/Rewards/',views.RewardPage,name='rewards'),
    path('awareness/',views.Awareness,name='awareness'),
    path('RegisterInfo/',views.updateInfo,name='updateInfo'),
    path('User/Success/',views.successpayment,name='success'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='App/auth/resetPassword.html'), name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='App/auth/passwordResetSent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='App/auth/passwordresetForm.html'), name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='App/auth/resetDone.html'), name='password_reset_complete'),
       
    path('activate/<uidb64>/<token>/',views.activate_user,name='activate')
]

UpCycle/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
]

urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'App.views.error_404'

App/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from phonenumber_field.modelfields import PhoneNumberField


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=50)
    about = models.TextField(blank=True,null=True)
    profile_pic = models.ImageField(default='avatar.png',upload_to='Profile')
    location = models.CharField(max_length=50,blank=True,null=True)
    street = models.CharField(max_length=50,blank=True,null=True)
    city = models.CharField(max_length=30,blank=True,null=True)
    state = models.CharField(max_length=30,blank=True,null=True)
    phone = PhoneNumberField(blank=True,null=True)
    is_email_verified = models.BooleanField(default=False)
    def __str__(self):
        return self.name


class Waste(models.Model):
    class Types(models.TextChoices):
        STEEL = "STEEL","Steel"
        BIODEGRADABLE = "BIO-DEGRADABLE","Bio-Degradable"
        PAPER = "PAPER","Paper"
        EWASTE = "E-WASTE","E-Waste"
    id = models.CharField(primary_key=True,unique=True,max_length=40)
    recycler = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='recycler')
    company = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='company')
    employee = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='employee')
    entry_date = models.DateField(null=True,blank=True)
    pickup_date = models.DateField(null=True,blank=True)
    dropdown_date = models.DateField(null=True,blank=True)
    weight = models.FloatField(null=True,blank=True)
    price = models.FloatField(null=True,blank=True)
    type = models.CharField(_("Types"),max_length=50,choices=Types.choices)
    pickup_done = models.BooleanField(default=False)
    dropdown_done = models.BooleanField(default=False)
    def __str__(self):
        return self.id

#RazorPay Order Schema
class Subscription(models.Model):
    name= models.ForeignKey(User,on_delete=models.CASCADE,primary_key=True,unique=True)
    subscription_id = models.CharField(max_length=100,null=True,blank=True)
    paid = models.BooleanField(default=False)
    subscription_date = models.DateTimeField(blank=True,null=True)
    subscription_end = models.DateTimeField(blank=True,null=True)
    amount = models.IntegerField(blank=True,null=True)
    rewardClaimed = models.IntegerField(default=0)
    def __str__(self):
        return self.name.username

App/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile,Waste

from PIL import Image

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(ModelForm):
    class Meta:   
        model = Profile
        fields = ['name','about','location','street','city','state','phone']

class ProfImageUpdateForm(ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    class Meta:
        model = Profile
        fields = ['profile_pic','x','y','width','height']
    def save(self):
        photo = super(ProfImageUpdateForm,self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        image = Image.open(photo.profile_pic.path)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((150, 150), Image.ANTIALIAS)
        resized_image.save(photo.profile_pic.path)
        return photo

class AddWasteForm(ModelForm):
    class Meta:
        model = Waste
        fields = ['id','company','type','weight','entry_date']

class SetDate(ModelForm):
    class Meta:
        model = Waste
        fields = ['id','employee','pickup_date','recycler','dropdown_date']

class Done(ModelForm):
    class Meta:
        model = Waste
        fields = ['id','pickup_done','dropdown_done']

App/templates/App/profileUpdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

{% extends 'App/profile.html' %}
{%load static%}

<body>
    {% block data %}
        <div class="flex relative">
            <button class="absolute top-[8px] right-[8px] p-[5px] rounded-md text-white bg-slate-900 text-[1.25rem] md:text-[1.5rem] closeUpdate"><i class="bi bi-pencil-square"></i></button>
            <div class="my-auto w-[50px] h-[50px] sm:w-[75px] sm:h-[75px] md:w-[100px] md:h-[100px] bg-slate-900 flex rounded-full overflow-hidden"><img src="{{user.profile.profile_pic.url}}" alt="" class="w-full"></div>
            <div class="ml-[10px] sm:ml-[20px] md:ml-[30px] my-auto"><h1 class="text-[1.25rem] sm:text-[1.5rem]">{{user.username}}</h1><h3 class="text-[1rem] sm:text-[1.25rem]">{{user.email}}</h3></div>
        </div>

            <div class="flex flex-col">
                <div>{{user.profile.name}}</div>
                <div>{{user.profile.about}}</div>
                <div>{{user.profile.location}}</div>
                <div>{{user.profile.street}}</div>
                <div>{{user.profile.city}}</div>
                <div>{{user.profile.state}}</div>
                <div>{{user.profile.phone}}</div>
            </div>

            <div class="relative bg-slate-900 text-white p-[10px] hidden" id="Update">
                <button class="absolute top-[10px] right-[10px] closeUpdate hidden" ><i class="bi bi-x-lg text-white text-[1.5rem]"></i></button>
            <form action="" method="POST" enctype="multipart/form-data" id="ProfileUpdate">
                {% csrf_token %}
                <h1 class="text-[1.5rem] sm:text-[2rem] font-bold text-center">Update Profile</h1>
                <div><label for="id_name">Name:</label><br><input class="bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" type="text" name="name" id="id_name" value="{{user.profile.name}}" required maxlength="50"></div>
                <div><label for="id_about">About:</label><br><textarea class="w-[300px] h-[150px] bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" name="about" id="id_about">{{user.profile.about}}</textarea></div>
                <div><label for="id_location">Location:</label><br><input class="w-[300px] bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" name="location" type="text" id="id_location" value="{{user.profile.location}}"></div>
                <div><label for="id_street">Street:</label><br><input class="w-[300px] bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" name="street" type="text" id="id_street" value="{{user.profile.street}}"></div>
                <div><label for="id_city">City:</label><br><input class="w-[300px] bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" name="city" type="text" id="id_city" value="{{user.profile.city}}"></div>
                <div><label for="id_state">State:</label><br><input class="w-[300px] bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" name="state" type="text" id="id_state" value="{{user.profile.state}}"></div>
                <div><label for="id_phone">Phone</label><br><input class="bg-[#f0f8ff5c] rounded-md text-[0.9rem] p-[5px]" type="tel" name="phone" value="{{user.profile.phone}}" id="id_phone"></div>
                <div><label for="id_profile_pic">Profile Picture:</label><br>"Currently: "<a href="{{user.profile.profile_pic.url}}">{{user.profile.profile_pic}}</a><br>"Change: "<input type="file" name="profile_pic" id="id_profile_pic" accept="image/*">
                    <input type="hidden" name="x" id="id_x"><input type="hidden" name="y" id="id_y"><input type="hidden" name="width" id="id_width"><input type="hidden" name="height" id="id_height">
                </div>
                <div class="flex w-full my-[15px]"><button class="mx-auto bg-white text-green-600 border-green-600 hover:bg-green-600 hover:text-white ease-in-out rounded-lg p-[3px] border-2" type="submit">Update</button><button class="mx-auto ease-in-out bg-white text-rose-600 border-rose-600 hover:bg-rose-600 hover:text-white border-2 p-[3px] rounded-lg" type="reset">Cancel</button></div>
            </form>  
            </div>

    

    <div class="fixed top-0 w-full h-screen flex bg-[#00000090] z-[999] hidden" id="modalCrop">
        <div class="relative flex m-auto p-[20px] w-[300px] sm:w-[600px] h-[500px] bg-white rounded-lg">
            <div class="modal-content w-full">
            <div class="modal-header">
                <button class="absolute top-[10px] right-[10px] closeModalCrop" ><i class="bi bi-x-lg text-black text-[20px]"></i></button>
                <h2 class="text-center text-[1.2rem]">Crop The Image</h2>
            </div>
            <div class="modal-body w-full h-[85%] flex"><img src="" id="image" class="max-w-[80%] max-h-[360px] my-auto mx-auto"></div>
            <div class="modal-footer absolute bottom-[20px]">
                <button type="button" class="js-crop-and-upload border-[1px] bg-white text-green-600 border-green-600 hover:bg-green-600 hover:text-white rounded-lg p-[3px]">Crop and Upload</button>
                <button type="button" class="border-[1px] bg-white text-rose-600 border-rose-600 hover:bg-rose-600 hover:text-white rounded-lg p-[3px] closeModalCrop">Cancel</button>
            </div>
            <div class="absolute top-[80%] right-[5%] zoom-bar bg-black text-white text-[15px] sm:text-[20px] px-[5px] w-max rounded-md"><button type="button" class="m-[5px] js-zoom-in"><i class="bi bi-zoom-in"></i></button><button type="button" class="m-[5px] js-zoom-out"><i class="bi bi-zoom-out"></i></button></div>
            </div>
        </div>
    </div>




<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(function () {
        $(".closeUpdate").click(function () {
            $("#Update").toggleClass("hidden");
            $(".closeUpdate").toggleClass("hidden");
        });

        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
        $("#id_profile_pic").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#image").attr("src", e.target.result);
                        $("#modalCrop").toggleClass("hidden");
                        $("#modalCrop").toggleClass("shown");
                    }
                reader.readAsDataURL(this.files[0]);
            }
        });
        $(".closeModalCrop").click(function () {
            $("#modalCrop").addClass("hidden");
            $("#modalCrop").toggleClass("shown");
        });

        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        $("#image").click(function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1/1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        });

        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });

        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#ProfileUpdate").submit();
        });
    });
</script>
{% endblock %}
    </body>
</html>

App/templates/App/wasteprod.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Waste</title>    
</head>

{% extends 'App/base.html' %}
{%load static%}

<body>
    {% block content %}
    <div class="content bg-slate-900 p-24">
        <div class="min-w-full font-space my-24">
            <h1 class="text-green-300 text-7xl font-bold ">Hello, {{user.profile.name}}</h1>
            <button type="button" class="closeAddWaste my-9 w-fit bg-green-300 px-2 rounded-md absolute right-24">Add Items For Recycling</button>
        </div>
        <div class="Table min-w-4/5 p-2 bg-slate-50 rounded-2xl overflow-auto">
            <table class="relative border-separate border-spacing-0 table-auto min-w-full bg-slate-50 text-sm opacity-90 text-center font-inter">
                <thead class="bg-slate-300">
                    <tr>
                        <th class="rounded-tl-xl text-center px-4 py-1 w-[150px] md:w-[300px]">ID</th>
                        <th class="px-4 py-1">Type</th>
                        <th class="px-4 py-1">Entry Date</th>
                        <th>Quantity</th>
                        <th>Approx. Price</th>
                        <th>Pickup Date</th>
                        <th class="rounded-tr-xl">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for waste in wastes %}
                    <tr>
                        <td class="text-left px-4 py-1 border-b border-slate-300 border-l flex">{{waste.id}}</td>
                        <td class="text-center px-4 py-1 border-b border-slate-300"><div class="font-bold">{{waste.type}}</div></td>
                        <td class="text-center px-4 py-1 border-b border-slate-300">{{waste.entry_date}}</td>
                        <td class="text-center py-1 border-b border-slate-300">{{waste.weight}}</td>
                        <td class="border-b border-slate-300">{{waste.weight}}</td>
                        <td class="border-b border-slate-300">{{waste.pickup_date}}</td>
                        <td class="border-b border-slate-300 border-r">
                            {% if waste.pickup_done %}
                            <button type="button" disabled class="bg-green-200 border-[1px] border-green-800 text-green-800 rounded-[3px] px-[3px] py-[2px] my-[3px]" >Picked Up</button>
                            {% else %}
                            <button type="button" disabled class="bg-red-200 border-[1px] border-red-800 text-red-800 rounded-[3px] px-[3px] py-[2px] my-[3px]" >Not Picked Up</button>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
            <div class="w-full text-[1rem] h-5 my-4 text-center">
                {% if wastes.has_previous %}
                <button class="p-[5px] m-[5px]" type="button"><a href="?page=1"><i class="bi bi-chevron-double-left"></i>First</a></button>
                <button class="p-[5px] m-[5px]" type="button"><a href="?page={{wastes.previous_page_number}}"><i class="bi bi-chevron-left"></i>Previous</a></button>
                {% endif %}
                <button class="p-[5px] m-[5px]" type="button">Page {{wastes.number}} of {{wastes.paginator.num_pages}}</button>
                {% if wastes.has_next %}
                <button class="p-[5px] m-[5px]" type="button"><a href="?page={{wastes.next_page_number}}">Next<i class="bi bi-chevron-right"></i></a></button>
                <button class="p-[5px] m-[5px]" type="button"><a href="?page={{wastes.paginator.num_pages}}">Last<i class="bi bi-chevron-double-right"></i></a></button>
                {% endif %}
            </div>   
        </div>
        <div class="flex flex-wrap gap-8 my-8 mt-16 justify-center">
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
                <div class="bg-slate-300 text-slate-900 h-60 min-w-[224px] max-w-[224px] rounded-2xl mb-5">
                    <div class="relative bg-zinc-50 w-4/5 h-32 mx-auto bottom-7 rounded-2xl overflow-hidden">
                        <img src="{% static '/IMGS/Paper.jpg' %}" class="h-full"/>
                    </div>
                    <h3 class="block text-center text-green-800 text-2xl mb-3">Paper</h3>
                    <p class="block text-center text-slate-800 text-lg">Price: <span id="price" class="slashed-zero">20</span> per Kg</p>
                </div>
        </div>
    </div>
    

    <div class="flex fixed top-0 left-0 w-full h-screen bg-[#00000080] z-[990] hidden" id="modalAddWaste">
        <div class="relative flex m-auto p-[20px] w-[300px] sm:w-[600px] bg-white rounded-lg">
            <button type="button" class="closeAddWaste absolute top-[10px] sm:top-[20px] right-[10px] sm:right-[20px] text-black"><i class="bi bi-x-lg text-[1.25rem]"></i></button>
            <form action="" method="POST" class="w-full">
                {% csrf_token %}
                <h1 class="text-center text-forestgreen text-[2rem] mb-[20px]">Add Waste</h1>
                <div class="mb-[25px] text-[1.05rem]"><label class="font-bold" for="id_id">ID:</label><input type="text" name="id" id="id_id" value="{{uuid}}" hidden> {{uuid}} </div>
                <div class="mb-[25px] text-[1.05rem] flex flex-wrap space-between">
                    <div class="mb-[10px] mr-[30px]"><label class="font-bold" for="id_company">Company Name:</label><input type="text" name="company" id="id_company" value="{{user.id}}" hidden> <span>{{user.username}}</span></div> 
                    <div><label class="font-bold" for="id_entry_date">Date:</label><input type="text" id="id_entry_date" name="entry_date" value="{{date}}" hidden> <span>{{date}}</span></div>
                </div>
                <div class="mb-[25px] text-[1.05rem] flex flex-wrap space-between">
                    <div class="mb-[10px] mr-[40px]"><label class="font-bold" for="id_weight">Weight:</label><input class="w-[150px] border-none outline-none" type="number" step="0.5" name="weight" id="id_weight"></div>
                    <div><label class="font-bold" for="id_type">Type:</label><select name="type" id="id_type" class="border-none outline-none">
                    <option value="-------" selected>-------</option>
                    <option value="STEEL">Steel</option>
                    <option value="BIO-DEGRADABLE">Bio-Degradable</option>
                    <option value="PAPER">Paper</option>
                    <option value="E-WASTE">E-Waste</option>
                    </select></div>
                </div>
                <div class="flex my-[25px] w-full">
                <button type="submit" class="mx-auto border-[1px] hover:bg-green-800 border-green-800 text-green-800 hover:text-white bg-white px-[5px] py-[3px] text-[1rem] rounded-[3px]">Submit</button>
                <button type="reset" class="closeAddWaste mx-auto border-[1px] hover:bg-red-800 border-red-800 text-red-800 hover:text-white bg-white px-[5px] py-[3px] text-[1rem] rounded-[3px]">Cancel</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(function () {
            $(".closeAddWaste").click(function (){
                $("#modalAddWaste").toggleClass("hidden");
            });
        });
    </script>
    {% endblock %}
</body>
</html>